name: app_updater
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.22.3
  jaspr_flutter_embed: ^0.4.10
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  jaspr_builder: ^0.22.3

jaspr:
  mode: static
  flutter: embedded

flutter:
  uses-material-design: true
